# Generated by Django 4.1.4 on 2023-04-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_profile_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='title',
            new_name='name',
        ),
    ]
