# Generated by Django 4.1.4 on 2023-04-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
