# Generated by Django 4.1.4 on 2023-04-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_title_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
