# Generated by Django 4.1.4 on 2023-04-25 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0013_alter_task_imgtask'),
        ('main', '0004_alter_enrollment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('solveTask', models.BooleanField(verbose_name='Решено задание')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.task')),
            ],
        ),
    ]
