# Generated by Django 4.1.3 on 2022-11-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('about', models.TextField(verbose_name='О курсе')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
    ]
