# Generated by Django 4.1.3 on 2022-11-27 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_curse_alter_subjects_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='curse',
            name='subject',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='subjects.subjects'),
            preserve_default=False,
        ),
    ]
