# Generated by Django 4.1.4 on 2023-03-28 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_curse_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('dateTime', models.DateTimeField(verbose_name='Дата и время занятия')),
                ('curse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.curse')),
            ],
        ),
    ]
