# Generated by Django 4.1.4 on 2023-04-10 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_remove_profile_curses_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curse',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curses', to='subjects.subjects'),
        ),
    ]
