# Generated by Django 4.1.4 on 2023-04-24 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_alter_curse_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='Номер задания')),
            ],
        ),
        migrations.CreateModel(
            name='ThemeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='Тема заданий')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.section')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('imgTask', models.ImageField(blank=True, upload_to='', verbose_name='Фото Задание')),
                ('answer', models.FloatField(verbose_name='Ответ')),
                ('themeTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.themetask')),
            ],
        ),
    ]
