# Generated by Django 4.1.4 on 2023-04-24 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_alter_task_themetask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themetask',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='subjects.section'),
        ),
    ]
