# Generated by Django 4.1.4 on 2023-04-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0012_alter_themetask_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='imgTask',
            field=models.ImageField(blank=True, upload_to='img/api/v1/task', verbose_name='Фото Задание'),
        ),
    ]
