# Generated by Django 4.1.4 on 2023-05-09 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0015_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='curse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='subjects.curse'),
        ),
    ]
