# Generated by Django 4.1.4 on 2023-05-14 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0016_alter_lesson_curse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='dateTime',
            new_name='date_time',
        ),
    ]
