# Generated by Django 4.1.4 on 2023-06-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0019_lesson_home_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='stream_status',
            field=models.CharField(default='offline', max_length=50, verbose_name='Статус трансляции'),
        ),
    ]
